// What the quiz asks about: only the numbered names of the class's parts drawing ("Lelievlet",
// 84 names; reference/book/onderdelen_lelievlet.json). The model has many more parts than have to
// be learnt. Per name: the drawing's number, the name as it is taught (where the owner corrected the
// sheet - Windvaan, Hanekam, Zwaardbout - his spelling), the ids of the parts that ARE it
// (`delen`: all of them light up, a click on any of them is right), parts that also count as right
// when clicked because they belong to it (`ook`), and whether it is worth showing on its own,
// without the rest of the boat (`los`): fittings and things with a shape of their own, not ropes,
// strakes or the named edges of a sail.
//
// `niveau` is the CWO Zeilen Kielboot level the name has to be known at: 1, 2 or 3.
// How each one was derived, with sources and page numbers: reference/parts/CWO_NIVEAUS.md.
//
// Not in the list: 61 Luchtkast and 62 Mangat (nothing in the model stands for them).

export const QUIZ = [
  { nr: 1, naam: 'Klauwval', niveau: 1, delen: ['klauwval'], ook: ['blok_klauwval'] },
  { nr: 2, naam: 'Windvaan', niveau: 3, delen: ['windvaan'], los: true },
  { nr: 3, naam: 'Piekenval', niveau: 1, delen: ['piekenval'], ook: ['blok_piekenval'] },
  { nr: 4, naam: 'Gaffeldraad', niveau: 3, delen: ['gaffeldraad'], ook: ['beslag_gaffel'] },
  { nr: 5, naam: 'Marllijn', niveau: 3, delen: ['marllijn_gaffel', 'marllijn_giek'] },
  { nr: 6, naam: 'Gaffel', niveau: 1, delen: ['gaffel'] },
  { nr: 7, naam: 'Tophoek van het grootzeil', niveau: 2, delen: ['grootzeil_tophoek'] },
  { nr: 8, naam: 'Zeillat', niveau: 3, delen: ['zeillatten'], los: true },
  { nr: 9, naam: 'Kleed', niveau: 3, delen: ['kleed'] },
  { nr: 10, naam: 'Want', niveau: 1, delen: ['want_bb', 'want_sb'] },
  { nr: 11, naam: 'Dirk of kraanlijn', niveau: 1, delen: ['kraanlijn'], ook: ['blok_kraanlijn'] },
  { nr: 12, naam: 'Grootzeil', niveau: 1, delen: ['grootzeil'], los: true },
  { nr: 13, naam: 'Achterlijk', niveau: 2, delen: ['grootzeil_achterlijk', 'fok_achterlijk'] },
  { nr: 14, naam: 'Schoothoek van het grootzeil', niveau: 2, delen: ['grootzeil_schoothoek'] },
  { nr: 15, naam: 'Wervel', niveau: 3, delen: ['wervel'], los: true },
  { nr: 16, naam: 'Pettenlijntje', niveau: 3, delen: ['pettenlijntje'] },
  { nr: 17, naam: 'Giek', niveau: 1, delen: ['giek'] },
  { nr: 18, naam: 'Grootschoot', niveau: 1, delen: ['grootschoot'], ook: ['blok_grootschoot_giek', 'blok_grootschoot_kuip'] },
  { nr: 19, naam: 'Onderlijk van het grootzeil', niveau: 2, delen: ['grootzeil_onderlijk'] },
  { nr: 20, naam: 'Halshoek van het grootzeil', niveau: 2, delen: ['grootzeil_halshoek'] },
  { nr: 21, naam: 'Lummelbeslag', niveau: 2, delen: ['lummelbeslag'], ook: ['mastband_lummel', 'lummelbout', 'lummelas'], los: true },
  { nr: 22, naam: 'Voorlijk van het grootzeil', niveau: 2, delen: ['grootzeil_voorlijk'] },
  { nr: 23, naam: 'Rijglijn', niveau: 1, delen: ['rijglijn'] },
  { nr: 24, naam: 'Klauw', niveau: 1, delen: ['klauw'], los: true },
  { nr: 25, naam: 'Klauwhoek', niveau: 2, delen: ['grootzeil_klauwhoek'] },
  { nr: 26, naam: 'Strop van de gaffel', niveau: 3, delen: ['strop_gaffel'], ook: ['harpje_strop'], los: true },
  { nr: 27, naam: 'Mastring', niveau: 3, delen: ['hommerring'], los: true },
  { nr: 28, naam: 'Mast', niveau: 1, delen: ['mast'] },
  { nr: 29, naam: 'Fokkenval', niveau: 1, delen: ['fokkenval'], ook: ['blok_fokkenval'] },
  { nr: 30, naam: 'Voorstag', niveau: 1, delen: ['voorstag'] },
  { nr: 31, naam: 'Fok', niveau: 1, delen: ['fok'], los: true },
  { nr: 32, naam: 'Voorlijk van de fok', niveau: 2, delen: ['fok_voorlijk'] },
  { nr: 33, naam: 'Tophoek van de fok', niveau: 2, delen: ['fok_tophoek'] },
  { nr: 34, naam: 'Halshoek of -broek van de fok', niveau: 2, delen: ['fok_halshoek'] },
  { nr: 35, naam: 'Onderlijk van de fok', niveau: 2, delen: ['fok_onderlijk'] },
  { nr: 36, naam: 'Schoothoek van de fok', niveau: 2, delen: ['fok_schoothoek'], ook: ['beslag_fok'] },
  { nr: 37, naam: 'Fokkenschoot', niveau: 1, delen: ['fokkenschoot'], ook: ['blok_fokkenschoot_bb', 'blok_fokkenschoot_sb'] },
  { nr: 38, naam: 'Kettinkje', niveau: 3, delen: ['kettinkje_fok'], los: true },
  { nr: 39, naam: 'Hanekam', niveau: 3, delen: ['hanekam'], los: true },
  { nr: 40, naam: 'Voorstagspanner', niveau: 3, delen: ['voorstagspanner', 'pelikaanhaak_ring'], los: true },
  { nr: 41, naam: 'Dolboord', niveau: 3, delen: ['dolboord_bb', 'dolboord_sb'], ook: ['spiegelrand', 'boegrand'] },
  { nr: 42, naam: 'Boeisel', niveau: 3, delen: ['boeisel_bb', 'boeisel_sb'], ook: ['dekcontour'] },
  { nr: 43, naam: 'Wantketting', niveau: 3, delen: ['wantketting_bb', 'wantketting_sb'], los: true },
  { nr: 44, naam: 'Kim', niveau: 3, delen: ['kim_bb', 'kim_sb'] },
  { nr: 45, naam: 'Vlak', niveau: 3, delen: ['vlak_bb', 'vlak_sb'] },
  { nr: 46, naam: 'Spiegel', niveau: 2, delen: ['spiegel'] },
  { nr: 47, naam: 'Scheg', niveau: 2, delen: ['scheg'], los: true },
  { nr: 48, naam: 'Zwaard', niveau: 1, delen: ['zwaard'], los: true },
  { nr: 49, naam: 'Zwaardbout', niveau: 3, delen: ['zwaardbout'], los: true },
  { nr: 50, naam: 'Zwaardloper', niveau: 3, delen: ['zwaardloper_onder', 'zwaardloper_boven'], ook: ['borgpen', 'kettinkje'], los: true },
  { nr: 51, naam: 'Zwaardkast', niveau: 1, delen: ['zwaardkast'], los: true },
  { nr: 52, naam: 'Mastkoker', niveau: 3, delen: ['mastkoker'], los: true },
  { nr: 53, naam: 'Mastbout', niveau: 1, delen: ['mastbout'], los: true },
  { nr: 54, naam: 'Grendelbout', niveau: 1, delen: ['grendelbout'], los: true },
  { nr: 55, naam: 'Kikker', niveau: 1, delen: ['kikkers_mastkoker', 'kikkers_voordek'], los: true },
  { nr: 56, naam: 'Dol', niveau: 1, delen: ['dol_sb_voor', 'dol_bb_voor', 'dol_sb_achter', 'dol_bb_achter'],
    ook: ['dolketting_sb_voor', 'dolketting_bb_voor', 'dolketting_sb_achter', 'dolketting_bb_achter'], los: true },
  { nr: 57, naam: 'Dolpot', niveau: 3, delen: ['dolpotten_bb', 'dolpotten_sb'], los: true },
  { nr: 58, naam: 'Berghout', niveau: 2, delen: ['berghout_bb', 'berghout_sb'] },
  { nr: 59, naam: 'Doft', niveau: 1, delen: ['doft_voor', 'doft_achter'], ook: ['dofthouders'] },
  { nr: 60, naam: 'Voordek', niveau: 1, delen: ['voordek'] },
  { nr: 63, naam: 'Buikdenning', niveau: 2, delen: ['buikdenning'], los: true },
  { nr: 64, naam: 'Sleepoog', niveau: 1, delen: ['sleepoog_boeg'], ook: ['sleepogen'], los: true },
  { nr: 65, naam: 'Hijsogen', niveau: 3, delen: ['hijsogen'], los: true },
  { nr: 66, naam: 'Grootschootoog', niveau: 3, delen: ['grootschootoog'], ook: ['grootschootoog_steun'], los: true },
  { nr: 67, naam: 'Leiogen van de fokkenschoot', niveau: 3, delen: ['leiogen_bb', 'leiogen_sb'], los: true },
  { nr: 68, naam: 'Landvastogen', niveau: 3, delen: ['landvastogen'], los: true },
  { nr: 69, naam: 'Achterdek', niveau: 1, delen: ['achterdek'] },
  { nr: 70, naam: 'Wrikgat', niveau: 3, delen: ['wrikgat'], los: true },
  { nr: 71, naam: 'Helmstok', niveau: 1, delen: ['helmstok'], ook: ['roerkop'], los: true },
  { nr: 72, naam: 'Roerkoning', niveau: 2, delen: ['roerkoning'] },
  { nr: 73, naam: 'Roerhaken', niveau: 3, delen: ['roerhaken'], los: true },
  { nr: 74, naam: 'Vingerlingen', niveau: 3, delen: ['vingerlingen'], los: true },
  { nr: 75, naam: 'Roerblad', niveau: 1, delen: ['roerblad'], los: true },
  { nr: 76, naam: 'Vlaggenstok', niveau: 3, delen: ['vlaggenstok'], los: true },
  { nr: 77, naam: 'Knop van de vlaggenstok', niveau: 3, delen: ['vlaggenstok_knop'], los: true },
  { nr: 78, naam: 'Vlag', niveau: 3, delen: ['vlag'], los: true },
  { nr: 79, naam: 'Boeg', niveau: 1, delen: ['boeg'] },
  { nr: 80, naam: 'Schootring', niveau: 1, delen: ['schootring'], los: true },
  { nr: 81, naam: 'Leuver', niveau: 1, delen: ['leuvers'], los: true },
  { nr: 82, naam: 'Hanepootloper', niveau: 3, delen: ['hanepootloper'], los: true },
  { nr: 83, naam: 'Dodemanseind', niveau: 3, delen: ['dodemanseind'] },
  { nr: 84, naam: 'Spant', niveau: 3, delen: ['spanten'], los: true },
];
