// What the quiz asks about: only the numbered names of the class's parts drawing ("Lelievlet",
// 84 names; reference/book/onderdelen_lelievlet.json). The model has many more parts than have to
// be learnt. Per name: the drawing's number, the name as it is taught (where the owner corrected the
// sheet - Windvaan, Hanekam, Zwaardbout - his spelling), the ids of the parts that ARE it
// (`delen`: all of them light up, a click on any of them is right), and parts that also count as
// right when clicked because they belong to it (`ook`).
//
// `niveau` is the CWO Zeilen Kielboot level the name has to be known at: 1, 2 or 3; `zeilen: false`
// leaves a name out of Zeilen altogether. `roeien` marks the names of the 40-part list of CWO
// Roeien (reference/book/ROEIEN.md), which has no levels: every one of them is asked at once.
// How each one was derived, with sources and page numbers: reference/parts/CWO_NIVEAUS.md.
//
// 85 and on are names of the roei list that the zeil drawing does not number.
//
// Not in the list: 61 Luchtkast and 62 Mangat (nothing in the model stands for them), and 77 Knop
// van de vlaggenstok (it is part of the Vlaggenstok).

export const QUIZ = [
  { nr: 1, naam: 'Klauwval', niveau: 1, delen: ['klauwval'], ook: ['blok_klauwval'] },
  { nr: 2, naam: 'Windvaan', niveau: 3, delen: ['windvaan'] },
  { nr: 3, naam: 'Piekenval', niveau: 1, delen: ['piekenval'], ook: ['blok_piekenval'] },
  { nr: 4, naam: 'Gaffeldraad', niveau: 3, delen: ['gaffeldraad'], ook: ['beslag_gaffel'] },
  { nr: 5, naam: 'Marllijn', niveau: 3, delen: ['marllijn_gaffel', 'marllijn_giek'] },
  { nr: 6, naam: 'Gaffel', niveau: 1, delen: ['gaffel'] },
  { nr: 7, naam: 'Tophoek van het grootzeil', niveau: 2, delen: ['grootzeil_tophoek'] },
  { nr: 8, naam: 'Zeillat', niveau: 3, delen: ['zeillatten'] },
  { nr: 9, naam: 'Kleed', niveau: 3, delen: ['kleed'] },
  { nr: 10, naam: 'Zijstag', niveau: 1, delen: ['want_bb', 'want_sb'] },
  { nr: 11, naam: 'Kraanlijn', niveau: 1, delen: ['kraanlijn'], ook: ['blok_kraanlijn'] },
  { nr: 12, naam: 'Grootzeil', niveau: 1, delen: ['grootzeil'] },
  { nr: 13, naam: 'Achterlijk', niveau: 2, delen: ['grootzeil_achterlijk', 'fok_achterlijk'] },
  { nr: 14, naam: 'Schoothoek van het grootzeil', niveau: 2, delen: ['grootzeil_schoothoek'] },
  { nr: 15, naam: 'Wervel', niveau: 3, delen: ['wervel'] },
  { nr: 16, naam: 'Pettenlijntje', niveau: 3, delen: ['pettenlijntje'] },
  { nr: 17, naam: 'Giek', niveau: 1, delen: ['giek'] },
  { nr: 18, naam: 'Grootschoot', niveau: 1, delen: ['grootschoot'], ook: ['blok_grootschoot_giek', 'blok_grootschoot_kuip'] },
  { nr: 19, naam: 'Onderlijk van het grootzeil', niveau: 2, delen: ['grootzeil_onderlijk'] },
  { nr: 20, naam: 'Halshoek van het grootzeil', niveau: 2, delen: ['grootzeil_halshoek'] },
  { nr: 21, naam: 'Lummelbeslag', niveau: 2, delen: ['lummelbeslag'], ook: ['mastband_lummel', 'lummelbout', 'lummelas'] },
  { nr: 22, naam: 'Voorlijk van het grootzeil', niveau: 2, delen: ['grootzeil_voorlijk'] },
  { nr: 23, naam: 'Rijglijn', niveau: 1, delen: ['rijglijn'] },
  { nr: 24, naam: 'Klauw', niveau: 1, delen: ['klauw'] },
  { nr: 25, naam: 'Klauwhoek', niveau: 2, delen: ['grootzeil_klauwhoek'] },
  { nr: 26, naam: 'Strop van de gaffel', niveau: 3, delen: ['strop_gaffel'], ook: ['harpje_strop'] },
  { nr: 27, naam: 'Mastring', niveau: 3, delen: ['hommerring'] },
  { nr: 28, naam: 'Mast', niveau: 1, delen: ['mast'] },
  { nr: 29, naam: 'Fokkenval', niveau: 1, delen: ['fokkenval'], ook: ['blok_fokkenval'] },
  { nr: 30, naam: 'Voorstag', niveau: 1, delen: ['voorstag'] },
  { nr: 31, naam: 'Fok', niveau: 1, delen: ['fok'] },
  { nr: 32, naam: 'Voorlijk van de fok', niveau: 2, delen: ['fok_voorlijk'] },
  { nr: 33, naam: 'Tophoek van de fok', niveau: 2, delen: ['fok_tophoek'] },
  { nr: 34, naam: 'Halshoek of -broek van de fok', niveau: 2, delen: ['fok_halshoek'] },
  { nr: 35, naam: 'Onderlijk van de fok', niveau: 2, delen: ['fok_onderlijk'] },
  { nr: 36, naam: 'Schoothoek van de fok', niveau: 2, delen: ['fok_schoothoek'] },
  { nr: 37, naam: 'Fokkenschoot', niveau: 1, delen: ['fokkenschoot'], ook: ['blok_fokkenschoot_bb', 'blok_fokkenschoot_sb'] },
  { nr: 38, naam: 'Kettinkje', niveau: 3, delen: ['kettinkje_fok'] },
  { nr: 39, naam: 'Hanekam', niveau: 3, roeien: true, delen: ['hanekam'] },
  { nr: 40, naam: 'Voorstagspanner', niveau: 3, delen: ['voorstagspanner', 'pelikaanhaak_ring'] },
  { nr: 41, naam: 'Dolboord', niveau: 3, roeien: true, delen: ['dolboord_bb', 'dolboord_sb'], ook: ['spiegelrand', 'boegrand'] },
  { nr: 42, naam: 'Boeisel', niveau: 3, roeien: true, delen: ['boeisel_bb', 'boeisel_sb'], ook: ['dekcontour'] },
  { nr: 43, naam: 'Wantketting', niveau: 3, delen: ['wantketting_bb', 'wantketting_sb'] },
  { nr: 44, naam: 'Kim', niveau: 3, roeien: true, delen: ['kim_bb', 'kim_sb'] },
  { nr: 45, naam: 'Vlak', niveau: 3, roeien: true, delen: ['vlak_bb', 'vlak_sb'] },
  { nr: 46, naam: 'Spiegel', niveau: 2, roeien: true, delen: ['spiegel'] },
  { nr: 47, naam: 'Scheg', niveau: 2, roeien: true, delen: ['scheg'] },
  { nr: 48, naam: 'Zwaard', niveau: 1, roeien: true, delen: ['zwaard'] },
  { nr: 49, naam: 'Zwaardbout', niveau: 3, roeien: true, delen: ['zwaardbout'] },
  { nr: 50, naam: 'Zwaardloper', niveau: 3, roeien: true, delen: ['zwaardloper_onder', 'zwaardloper_boven'], ook: ['borgpen', 'kettinkje'] },
  { nr: 51, naam: 'Zwaardkast', niveau: 1, roeien: true, delen: ['zwaardkast'] },
  { nr: 52, naam: 'Mastkoker', niveau: 3, roeien: true, delen: ['mastkoker'] },
  { nr: 53, naam: 'Mastbout', niveau: 1, delen: ['mastbout'] },
  { nr: 54, naam: 'Grendelbout', niveau: 1, roeien: true, delen: ['grendelbout'] },
  { nr: 55, naam: 'Kikker', niveau: 1, roeien: true, delen: ['kikkers_mastkoker', 'kikkers_voordek'] },
  { nr: 56, naam: 'Dol', niveau: 1, roeien: true, delen: ['dol_sb_voor', 'dol_bb_voor', 'dol_sb_achter', 'dol_bb_achter'],
    ook: ['dolketting_sb_voor', 'dolketting_bb_voor', 'dolketting_sb_achter', 'dolketting_bb_achter'] },
  { nr: 57, naam: 'Dolpot', niveau: 3, roeien: true, delen: ['dolpotten_bb', 'dolpotten_sb'] },
  { nr: 58, naam: 'Berghout', niveau: 2, roeien: true, delen: ['berghout_bb', 'berghout_sb'] },
  { nr: 59, naam: 'Doft', niveau: 1, roeien: true, delen: ['doft_voor', 'doft_achter'], ook: ['dofthouders'] },
  { nr: 60, naam: 'Voordek', niveau: 1, roeien: true, delen: ['voordek'] },
  { nr: 63, naam: 'Vlonder', niveau: 2, roeien: true, delen: ['buikdenning'] },
  { nr: 64, naam: 'Sleepoog', niveau: 1, roeien: true, delen: ['sleepoog_boeg'], ook: ['sleepogen'] },
  { nr: 65, naam: 'Hijsogen', niveau: 3, roeien: true, delen: ['hijsogen'] },
  { nr: 66, naam: 'Grootschootoog', niveau: 3, delen: ['grootschootoog'], ook: ['grootschootoog_steun'] },
  { nr: 67, naam: 'Leiogen van de fokkenschoot', niveau: 3, delen: ['leiogen_bb', 'leiogen_sb'] },
  { nr: 68, naam: 'Landvastogen', niveau: 3, roeien: true, delen: ['landvastogen'] },
  { nr: 69, naam: 'Achterdek', niveau: 1, roeien: true, delen: ['achterdek'] },
  { nr: 70, naam: 'Wrikgat', niveau: 3, roeien: true, delen: ['wrikgat'] },
  { nr: 71, naam: 'Helmhout', niveau: 1, roeien: true, delen: ['helmstok'], ook: ['roerkop'] },
  { nr: 72, naam: 'Roerkoning', niveau: 2, roeien: true, delen: ['roerkoning'] },
  { nr: 73, naam: 'Roerhaken', niveau: 3, roeien: true, delen: ['roerhaken'] },
  { nr: 74, naam: 'Vingerlingen', niveau: 3, roeien: true, delen: ['vingerlingen'] },
  { nr: 75, naam: 'Roerblad', niveau: 1, roeien: true, delen: ['roerblad'] },
  { nr: 76, naam: 'Vlaggenstok', niveau: 3, roeien: true, delen: ['vlaggenstok'] },
  { nr: 78, naam: 'Vlag', niveau: 3, roeien: true, delen: ['vlag'] },
  { nr: 79, naam: 'Boeg', niveau: 1, roeien: true, delen: ['boeg'] },
  { nr: 80, naam: 'Schootring', niveau: 1, delen: ['schootring'] },
  { nr: 81, naam: 'Leuver', niveau: 1, delen: ['leuvers'] },
  { nr: 82, naam: 'Hanepootloper', niveau: 3, delen: ['hanepootloper'] },
  { nr: 83, naam: 'Dodemanseind', niveau: 3, delen: ['dodemanseind'] },
  { nr: 84, naam: 'Spant', niveau: 3, roeien: true, delen: ['spanten'] },
  { nr: 85, naam: 'Riem', zeilen: false, roeien: true, delen: ['riem_sb', 'riem_bb'], ook: ['wrikriem'] },
];
